Ability to swap to new region - release-1.0 (#264)
* Update ci.yml

* oops

* names and echos

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,6 +67,20 @@ jobs:
         id: infra
         shell: pwsh
         run: |
+          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
+          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
+          echo "Actions agent running in Azure region $region"
+          
+          $allowedRegions = "${{ secrets.COSMOS_ALLOWED_REGIONS }}".split(',')
+          if (!$allowedRegions.contains($region))
+          {
+            echo "Region '$region' not currently allowed for Cosmos DB."
+            $randomIndex = Get-Random -Minimum 0 -Maximum $allowedRegions.length
+            $region = $allowedRegions[$randomIndex]
+            echo "Region randomly reset to $region"
+          }
+          
           $rand = Get-Random
           $cosmosname = "psw-cosmosdb-$($rand)"
           $storagename = "pswtables$($rand)"
@@ -75,7 +89,15 @@ jobs:
           $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
 
           echo "Creating CosmosDB database account $cosmosname (This can take awhile.)"
-          $acctDetails = az cosmosdb create --name $cosmosname --resource-group GitHubActions-RG --capabilities EnableServerless --tags Package=CosmosPersistence RunnerOS=${{ runner.os }} $dateTag | ConvertFrom-Json
+          $acctDetails = az cosmosdb create --name $cosmosname --location regionName=$region --resource-group GitHubActions-RG --capabilities EnableServerless --tags Package=CosmosPersistence RunnerOS=${{ runner.os }} $dateTag | ConvertFrom-Json
+          
+          if(!$acctDetails || !$acctDetails.documentEndpoint)
+          {
+            echo "Account creation failed. $acctDetails"
+            echo "If Azure is reporting demand too high for this region, refer to documentation for COSMOS_ALLOWED_REGIONS secret and consider updating."
+            exit 1;
+          }
+          
           $documentEndpoint = $acctDetails.documentEndpoint
           echo "::add-mask::$documentEndpoint"
 
@@ -88,7 +110,7 @@ jobs:
           $dbDetails = az cosmosdb sql database create --name CosmosDBPersistence --account-name $cosmosname --resource-group GitHubActions-RG | ConvertFrom-Json
 
           echo "Creating storage account for NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.AcceptanceTests (This can take awhile.)"
-          $storageDetails = az storage account create --name $storagename --resource-group GitHubActions-RG --sku Standard_LRS | ConvertFrom-Json
+          $storageDetails = az storage account create --name $storagename --location $region --resource-group GitHubActions-RG --sku Standard_LRS | ConvertFrom-Json
 
           echo "Getting storage account keys"
           $storageKeyDetails = az storage account keys list --account-name $storagename --resource-group GitHubActions-RG | ConvertFrom-Json
@@ -120,7 +142,10 @@ jobs:
         continue-on-error: true
         shell: pwsh
         run: |
+          echo "Deleting storage account ${{ steps.infra.outputs.storagename }}"
           $ignore = az storage account delete --resource-group GitHubActions-RG --name ${{ steps.infra.outputs.storagename }} --yes
+
+          echo "Deleting Cosmos DB account ${{ steps.infra.outputs.cosmosname }}"
 
           # Use this once cosmosdb delete offers --no-wait argument, until then, it takes too long (~7m) and we use curl instead
           #$ignore = az cosmosdb delete --resource-group GitHubActions-RG --name ${{ steps.infra.outputs.cosmosname }} --yes
@@ -129,5 +154,5 @@ jobs:
           $credentials = '${{ secrets.AZURE_ACI_CREDENTIALS }}' | ConvertFrom-Json
           $token = curl -X POST -d "grant_type=client_credentials&client_id=$($credentials.clientId)&client_secret=$($credentials.clientSecret)&resource=https%3A%2F%2Fmanagement.azure.com%2F" https://login.microsoftonline.com/$($credentials.tenantId)/oauth2/token | ConvertFrom-Json
           $authHeader = "Authorization: Bearer $($token.access_token)"
-          $resourceUrl = "https://management.azure.com${{ steps.infra.outputs.comsosAccountId }}?api-version=2021-04-15"
+          $resourceUrl = "https://management.azure.com/subscriptions/${{ secrets.AZURE_AUTOMATEDTESTING_SUBSCRIPTION_ID }}/resourceGroups/GitHubActions-RG/providers/Microsoft.DocumentDB/databaseAccounts/${{ steps.infra.outputs.cosmosname }}?api-version=2021-04-15"
           curl -X DELETE $resourceUrl -H $authHeader -H "Content-Type: application/json" --silent
